// Maps French vocabulary meanings to visual emoji illustrations
// Used to add visual context to Arabic vocabulary learning

const illustrationMap: Record<string, string> = {
  // Niveau 1 - Alphabet vocabulary
  "je / moi": "🙋",
  "père": "👨",
  "mère": "👩",
  "papa": "👨‍👦",
  "porte": "🚪",
  "il s'est repenti": "🤲",
  "fille": "👧",
  "maison": "🏠",
  "ferme / stable": "⚓",
  "trois": "3️⃣",
  "il a apporté": "📦",
  "montagne": "🏔️",
  "amour / grain": "❤️",
  "recherche": "🔍",
  "pain": "🍞",
  "frère": "👦",
  "poulet": "🐔",
  "nouveau": "✨",
  "or": "🥇",
  "professeur": "👨‍🏫",
  "homme": "👨",
  "mer": "🌊",
  "huile": "🫒",
  "cause / raison": "💡",
  "leçon": "📚",
  "arbre": "🌳",
  "soleil": "☀️",
  "matin": "🌅",
  "patience": "🧘",
  "terre": "🌍",
  "œuf(s)": "🥚",
  "médecin": "👨‍⚕️",
  "ligne / écriture": "✏️",
  "midi": "🕛",
  "mémorisation": "🧠",
  "arabe": "🇸🇦",
  "science / savoir": "🔬",
  "corbeau": "🐦‍⬛",
  "petit": "🐣",
  "joie": "😊",
  "laine": "🧶",
  "cœur": "❤️",
  "ami": "🤝",
  "livre": "📖",
  "grand": "📏",
  "nuit": "🌙",
  "beauté": "🌸",
  "école": "🏫",
  "eau": "💧",
  "lumière": "💡",
  "fleuve / rivière": "🏞️",
  "ceci / celui-ci": "👉",
  "mot / parole": "💬",
  "garçon / enfant": "👦",
  "main": "✋",
  "jour": "📅",

  // Niveau 2 - Grammar vocabulary
  "il a écrit": "✍️",
  "des livres": "📚",
  "un livre": "📖",
  "une porte": "🚪",
  "une lumière": "💡",
  "grand(e)": "📏",
  "le livre": "📖",
  "la porte": "🚪",
  "le soleil": "☀️",
  "la lune": "🌙",
  "l'école": "🏫",
  "l'élève": "👨‍🎓",
  "il": "👤",
  "elle": "👩",
  "tu (masc.)": "🫵",
  "tu (fém.)": "🫵",
  "nous": "👥",
  "dans la maison": "🏠",
  "sur la table": "🪑",
  "de l'école": "🏫",
  "vers la mosquée": "🕌",
  "il a mangé": "🍽️",
  "elle a bu": "🥤",
  "ils ont étudié": "📖",
  "nous avons joué": "⚽",
  "le garçon est grand": "👦",
  "la fille est belle": "👧",
  "le professeur est dans la classe": "👨‍🏫",
  "la maison est grande": "🏠",
  "rouge": "🔴",
  "bleu": "🔵",
  "vert": "🟢",
  "beau / belle": "✨",
  "un homme": "👨",
  "une femme": "👩",
  "des hommes": "👥",
  "des femmes": "👩‍👩‍👧",
  "deux livres": "📚",
  "deux portes": "🚪",
  "des élèves": "👨‍🎓",
  "des professeurs": "👨‍🏫",
  "ici": "📍",
  "là-bas": "👉",
  "maintenant": "⏰",
  "hier": "📆",
  "demain": "🗓️",
  "toujours": "♾️",
  "ne... pas (négation verbale)": "🚫",
  "n'est pas (négation nominale)": "❌",
  "il n'a pas écrit": "🚫",
  "il n'est pas professeur": "❌",
  "que / quoi ?": "❓",
  "qui ?": "🤔",
  "où ?": "📍",
  "comment ?": "💭",
  "quand ?": "⏰",
  "pourquoi ?": "🤷",
  "il mange": "🍽️",
  "il étudie": "📖",
  "il jouera": "⚽",
  "elle écrira": "✍️",
  "une voiture neuve": "🚗",
  "un livre utile": "📖",
  "un grand garçon": "👦",
  "un professeur actif": "👨‍🏫",

  // Additional common words
  "chat": "🐱",
  "chien": "🐕",
  "étoile": "⭐",
  "lune": "🌙",
  "ciel": "🌤️",
  "fleur": "🌺",
  "jardin": "🌷",
  "mosquée": "🕌",
  "classe": "🏫",
  "stylo": "🖊️",
  "cahier": "📓",
  "table": "🪑",
  "chaise": "🪑",
  "voiture": "🚗",
  "avion": "✈️",
  "bateau": "🚢",
  "nourriture": "🍲",
  "fruit": "🍎",
  "famille": "👨‍👩‍👧‍👦",
  "sœur": "👧",
  "fils": "👦",
  "bébé": "👶",
  "marché": "🛒",
  "ville": "🏙️",
  "pays": "🗺️",
  "parc": "🌳",
  "hôpital": "🏥",
  "sport": "⚽",
  "cuisine": "👨‍🍳",
  "dessin": "🎨",
  "musique": "🎵",
  "travail": "💼",
  "voyage": "✈️",
};

/**
 * Returns an emoji illustration for a given French meaning.
 * Tries exact match first, then partial match.
 */
export function getIllustration(meaning: string): string | null {
  // Exact match
  const lower = meaning.toLowerCase().trim();
  if (illustrationMap[lower]) return illustrationMap[lower];

  // Check each key for partial match
  for (const [key, emoji] of Object.entries(illustrationMap)) {
    if (lower.includes(key) || key.includes(lower)) {
      return emoji;
    }
  }

  return null;
}
